[metadata]
name = binding-affinity-prediction-deepdta
version = 0.1.0
author = Phuc Pham
author_email = phpham@uab.edu
description = PyTorch implementation of DeepDTA for drug-target binding affinity prediction
long_description = file: README.md
long_description_content_type = text/markdown
url = github_link
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
install_requires =
    torch>=2.0
    numpy
    scikit-learn
    matplotlib
    pyyaml
    tqdm
